runs-on: ubuntu-latest
on:
  push: ['main']
  pull_request: ['main']
job:
  run_suites:
    requirements: 'requirements/requirements.txt'
    
    train_dataset: 'dc_get_assets.py:get_train_dataset'
    test_dataset: 'dc_get_assets.py:get_test_dataset'
    model: 'dc_get_assets.py:load_model'

    # suites: ['deepchecks.tabular.suites:data_integrity', 'suites.py:validation_custom_suite']
    suites: ['basic_model_suite.py:my_model_evaluation']